[programs.localnet]
mysolanaapp = "6BU2RshNEB6MtQmbKN2WvyDcMLEoqivZf2vxt8J6UqYH"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/home/rance/.config/solana/id.json"

[scripts]
test = "mocha -t 1000000 tests/"
